# Generated by Django 5.2 on 2025-04-27 23:17

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Tasks',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, null=True, verbose_name='Tarea')),
                ('description', models.CharField(max_length=255, verbose_name='Descripción')),
                ('status', models.CharField(choices=[('to_do', 'Sin avance'), ('in_progress', 'En proceso'), ('done', 'Hecho')], max_length=50, verbose_name='Opciones')),
                ('created', models.DateTimeField(auto_now_add=True, verbose_name='Fecha de creación')),
                ('updated', models.DateTimeField(auto_now_add=True, verbose_name='Fecha de actualización')),
                ('status_delete', models.BooleanField(default=False)),
            ],
            options={
                'db_table': 'tasks',
            },
        ),
    ]
